### ISSUE TITLE
Hero's Mod Group Function

### ISSUE THREAD

**Issue by NightingaleZK** [JavidPack/HEROsMod#57]
I really love Hero's Mod because it is a fully functional array of server management and commands, but an issue came up when I was trying to create groups. I tried making it to where staff had all admin privileges and all other players were set to default, which in my mind I thought this meant normal Terraria commands, but something went wrong in the process. My friends can't do anything except for kill and move around, interacting with NPCs, but they can't build or break anything. I tried editing their roles to fix this issue, but the icon that display all the users no longer appears for me since I joined under the Staff group I made which was supposed to have all privileges. I have tried uninstalling the mod, uninstalling and reinstalling Terraria and tModLoader, but nothing I do seems to fix this problem. I don't know if there is any command I could put in to override this, but any response to this issue would be helpful as googling this particular issue up came to nothing.

**Comment by JavidPack** [comment]
It might be easier to work though this on the discord chat, but it sounds like the issue is you aren't admin. Having all the permissions isn't the same as Admin, so your Staff role might not be able to do everything you want.

You can try logging into the admin username, or just start over by deleting "Documents\My Games\Terraria\ModLoader\HEROsModDatabase.json" and then launching the server again. The normal default group should be able to do all the normal stuff. There is also the possibility that you did something with regions that would prevent mining in specific areas, not sure. If it were me, I'd just start the configuration over again and try again.

**Comment by NightingaleZK** [comment]
I did exactly as recommended and it worked swimmingly, thank you so much! I believe I did something horribly wrong when creating groups so I'm going to try googling a guide up on how to work that out properly, but thank you again!
